# typed: false
# frozen_string_literal: true

# DO NOT EDIT. Generated by release workflow.
class Io < Formula
  desc "Personal AI assistant TUI backed by Claude Code or Codex CLI"
  homepage "https://github.com/paradise-runner/io"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/paradise-runner/io/releases/download/v0.0.1/io-darwin-arm64.zip"
      sha256 "d6b53f882464c742863830cf8dd7854bd5277c6f6297b4516f13aa257fe0d8b3"

      def install
        bin.install "io-darwin-arm64" => "io"
      end
    else
      url "https://github.com/paradise-runner/io/releases/download/v0.0.1/io-darwin-amd64.zip"
      sha256 "7133164ae97d61a42b2cceeafdb7bf7e3f86264512a8c2f85a14d38018814d6f"

      def install
        bin.install "io-darwin-amd64" => "io"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/paradise-runner/io/releases/download/v0.0.1/io-linux-arm64.zip"
      sha256 "2048d752ada66d4cad7bb1997f4902730f0741debbb7764c18e789a6d4d00ddd"

      def install
        bin.install "io-linux-arm64" => "io"
      end
    else
      url "https://github.com/paradise-runner/io/releases/download/v0.0.1/io-linux-amd64.zip"
      sha256 "f93c683c5584889e1dfa3a1a51cb785a8ce9614ea12f6e3c59af56ac14e3f4f0"

      def install
        bin.install "io-linux-amd64" => "io"
      end
    end
  end

  def caveats
    <<~EOS
      io drives an authenticated Claude Code or Codex CLI. Install and authenticate at least one before launching io.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/io --version")
  end
end
