# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaleidoscope < Formula
  desc "Run multiple AI models in parallel, compare outputs, choose the best solution"
  homepage "https://paradise-runner.github.io/kaleidoscope/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/paradise-runner/opencode/releases/download/v0.1.0/kaleidoscope-darwin-arm64.zip"
      sha256 "061b9f79cb43a0cc52e277f1b94d3eb1a8d98d6fdd42533a9d60da20aa972e54"

      def install
        bin.install "kaleidoscope"
      end
    end
  end

end
