# typed: false
# frozen_string_literal: true

# DO NOT EDIT. Generated by release workflow.
class Toast < Formula
  desc "In-terminal IDE for quick file edits"
  homepage "https://github.com/paradise-runner/toast"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/paradise-runner/toast/releases/download/v0.0.4/toast-darwin-arm64.zip"
      sha256 "a7ab13839882423302582930fa790f9b8403a888d4db7a54a674569a72b37d34"

      def install
        bin.install "toast-darwin-arm64" => "toast"
      end
    else
      url "https://github.com/paradise-runner/toast/releases/download/v0.0.4/toast-darwin-amd64.zip"
      sha256 "a937c80d3c50407b457807b15096d61f673347cac1411287995f9f9158c05e4e"

      def install
        bin.install "toast-darwin-amd64" => "toast"
      end
    end
  end

end
