# typed: false
# frozen_string_literal: true

# DO NOT EDIT. Generated by release workflow.
class Toast < Formula
  desc "In-terminal IDE for quick file edits"
  homepage "https://github.com/paradise-runner/toast"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/paradise-runner/toast/releases/download/v0.1.7/toast-darwin-arm64.zip"
      sha256 "7fb72505404d4b19f859161380278ea3dd8944b0494468075bffd90f158e1842"

      def install
        bin.install "toast-darwin-arm64" => "toast"
      end
    else
      url "https://github.com/paradise-runner/toast/releases/download/v0.1.7/toast-darwin-amd64.zip"
      sha256 "cd215a74bcf12c99367e75c2f1452bb05ac3399c13fc0f5ffd68a1bef8466da4"

      def install
        bin.install "toast-darwin-amd64" => "toast"
      end
    end
  end

end
